// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");
var Grid$ReactHooksTemplate = require("./Grid.bs.js");
var Hooks$ReactHooksTemplate = require("./Hooks.bs.js");
var GridRow$ReactHooksTemplate = require("./GridRow.bs.js");
var GridItem$ReactHooksTemplate = require("./GridItem.bs.js");
var GridTasks$ReactHooksTemplate = require("./GridTasks.bs.js");

var container = Css.style(/* :: */[
      Css.height(Css.vh(100)),
      /* :: */[
        Css.display(Css.flexBox),
        /* :: */[
          Css.background(Css.hex("fff")),
          /* [] */0
        ]
      ]
    ]);

var Styles = /* module */[/* container */container];

function renderItems(maxRowItems, width) {
  var items_000 = React.createElement(GridItem$ReactHooksTemplate.make, {
        width: width,
        message: "Grid Item 1",
        key: "1"
      });
  var items_001 = /* :: */[
    React.createElement(GridItem$ReactHooksTemplate.make, {
          width: width,
          message: "Grid Item 2",
          key: "2"
        }),
    /* :: */[
      React.createElement(GridItem$ReactHooksTemplate.make, {
            width: width,
            message: "Grid Item 3",
            key: "3"
          }),
      /* :: */[
        React.createElement(GridItem$ReactHooksTemplate.make, {
              width: width,
              message: "Grid Item 4",
              key: "4"
            }),
        /* :: */[
          React.createElement(GridItem$ReactHooksTemplate.make, {
                width: width,
                message: "Grid Item 5",
                key: "5"
              }),
          /* [] */0
        ]
      ]
    ]
  ];
  var items = /* :: */[
    items_000,
    items_001
  ];
  var rows = GridTasks$ReactHooksTemplate.splitByRow(items, maxRowItems);
  return $$Array.mapi((function (i, row) {
                return React.createElement(GridRow$ReactHooksTemplate.make, {
                            children: row,
                            key: String(i) + "_row"
                          });
              }), rows);
}

function Component1(Props) {
  var vw = Hooks$ReactHooksTemplate.useVW(/* () */0);
  var lg = Hooks$ReactHooksTemplate.useMedia("(min-width: 1200px)");
  var md = Hooks$ReactHooksTemplate.useMedia("(min-width: 992px)");
  var sm = Hooks$ReactHooksTemplate.useMedia("(min-width: 768px)");
  var maxRowItems = lg ? 4 : (
      md ? 3 : (
          sm ? 2 : 1
        )
    );
  console.log(maxRowItems);
  return React.createElement("div", {
              className: container
            }, React.createElement(Grid$ReactHooksTemplate.make, {
                  itemWidth: Caml_int32.div(vw, maxRowItems),
                  render: (function (param) {
                      return renderItems(maxRowItems, param);
                    })
                }));
}

var make = Component1;

exports.Styles = Styles;
exports.renderItems = renderItems;
exports.make = make;
/* container Not a pure module */
