// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var Grid$ReactHooksTemplate = require("./Grid.bs.js");

var container = Css.style(/* :: */[
      Css.height(Css.vh(100)),
      /* :: */[
        Css.display(Css.flexBox),
        /* :: */[
          Css.background(Css.hex("fff")),
          /* [] */0
        ]
      ]
    ]);

var Styles = /* module */[/* container */container];

function Component1(Props) {
  return React.createElement("div", {
              className: container
            }, React.createElement(Grid$ReactHooksTemplate.make, { }));
}

var make = Component1;

exports.Styles = Styles;
exports.make = make;
/* container Not a pure module */
