// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var GridRow$ReactHooksTemplate = require("./GridRow.bs.js");

var container = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.flexDirection(Css.column),
        /* [] */0
      ]
    ]);

var Styles = /* module */[/* container */container];

function Grid(Props) {
  var itemWidth = Props.itemWidth;
  return React.createElement("div", {
              className: container
            }, React.createElement(GridRow$ReactHooksTemplate.make, {
                  itemWidth: itemWidth
                }));
}

var make = Grid;

exports.Styles = Styles;
exports.make = make;
/* container Not a pure module */
