// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");

var container = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.backgroundColor(Css.hex("ccc")),
        /* [] */0
      ]
    ]);

var Styles = /* module */[/* container */container];

function GridRow(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: container
            }, children);
}

var make = GridRow;

exports.Styles = Styles;
exports.make = make;
/* container Not a pure module */
