// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

var container = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.flexDirection(Css.column),
        /* [] */0
      ]
    ]);

var Styles = /* module */[/* container */container];

function Grid(Props) {
  var itemWidth = Props.itemWidth;
  var render = Props.render;
  return React.createElement("div", {
              className: container
            }, Curry._1(render, itemWidth));
}

var make = Grid;

exports.Styles = Styles;
exports.make = make;
/* container Not a pure module */
