// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");

function container(w) {
  return Css.style(/* :: */[
              Css.width(Css.px(w)),
              /* :: */[
                Css.height(Css.pxFloat(1.2 * w)),
                /* [] */0
              ]
            ]);
}

var Styles = /* module */[/* container */container];

function GridItem(Props) {
  var width = Props.width;
  return React.createElement("div", {
              className: container(width)
            }, "Grid Item");
}

var make = GridItem;

exports.Styles = Styles;
exports.make = make;
/* Css Not a pure module */
