// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var GridItem$ReactHooksTemplate = require("./GridItem.bs.js");

var container = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.backgroundColor(Css.hex("ccc")),
        /* [] */0
      ]
    ]);

var Styles = /* module */[/* container */container];

function GridRow(Props) {
  var itemWidth = Props.itemWidth;
  return React.createElement("div", {
              className: container
            }, React.createElement(GridItem$ReactHooksTemplate.make, {
                  width: itemWidth
                }), React.createElement(GridItem$ReactHooksTemplate.make, {
                  width: itemWidth
                }), React.createElement(GridItem$ReactHooksTemplate.make, {
                  width: itemWidth
                }), React.createElement(GridItem$ReactHooksTemplate.make, {
                  width: itemWidth
                }), React.createElement(GridItem$ReactHooksTemplate.make, {
                  width: itemWidth
                }), React.createElement(GridItem$ReactHooksTemplate.make, {
                  width: itemWidth
                }));
}

var make = GridRow;

exports.Styles = Styles;
exports.make = make;
/* container Not a pure module */
