// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");

function container(w) {
  return Css.style(/* :: */[
              Css.display(Css.flexBox),
              /* :: */[
                Css.alignItems(Css.center),
                /* :: */[
                  Css.justifyContent(Css.center),
                  /* :: */[
                    Css.width(Css.px(w)),
                    /* :: */[
                      Css.border(Css.px(1), Css.solid, Css.hex("000")),
                      /* :: */[
                        Css.height(Css.pxFloat(1.2 * w)),
                        /* :: */[
                          Css.backgroundColor(Css.hex("ccc")),
                          /* [] */0
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

var Styles = /* module */[/* container */container];

function GridItem(Props) {
  var width = Props.width;
  var message = Props.message;
  return React.createElement("div", {
              className: container(width)
            }, message);
}

var make = GridItem;

exports.Styles = Styles;
exports.make = make;
/* Css Not a pure module */
