// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function useVW(param) {
  var match = React.useState((function () {
          return window.innerWidth;
        }));
  var setVW = match[1];
  React.useEffect((function () {
          var listener = function (param) {
            return Curry._1(setVW, (function (param) {
                          return window.innerWidth;
                        }));
          };
          window.addEventListener("resize", listener);
          return (function (param) {
                    window.removeEventListener("resize", listener);
                    return /* () */0;
                  });
        }), ([]));
  return match[0];
}

function useMedia(query) {
  var match = React.useState((function () {
          return window.matchMedia(query).matches;
        }));
  var setMatches = match[1];
  React.useEffect((function () {
          var listener = function (param) {
            return Curry._1(setMatches, (function (param) {
                          return window.matchMedia(query).matches;
                        }));
          };
          window.addEventListener("resize", listener);
          return (function (param) {
                    window.removeEventListener("resize", listener);
                    return /* () */0;
                  });
        }), ([]));
  return match[0];
}

exports.useVW = useVW;
exports.useMedia = useMedia;
/* react Not a pure module */
